### ISSUE TITLE
Access to image dimensions

### ISSUE THREAD

**Issue by Y0hy0h** [dillonkearns/elm-pages#104]
Similar to #36, it would be useful to have access to the actual image dimensions.

My use case is that I would like to set the `width` and `height` HTML attributes on the `<img>`, to prevent the layout from popping after the image has been loaded. By setting the intrinsic dimensions, the browser is able to reserve the appropriate amount of space even before the image resource is loaded.

I imagine it could look something like `ImagePath.width Pages.images.funnyGif`. That means elm-pages would statically store the dimensions of all images in `Pages` from where I could simply access it.

**Comment by dillonkearns** [comment]
Hello! Yes, I agree, this would be great! I've got some big things on the roadmap right now that I'm focused on, so I won't have bandwidth to work on this improvement in the near-term.

I would love a contribution on this functionality if anyone is interested, though!

We already have sharp as a dependency of the favicon package, so it's installing for the `elm-pages` package as is. If we add `sharp` as a direct `devDependency` in the package.json, then we'll have access to this:

https://sharp.pixelplumbing.com/api-input

That includes a simple API for grabbing the dimensions.

Then we would need to wire that data through from the JS here:

https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/generator/src/generate-records.js#L43-L53

Add an argument to the `buildPage` call that's generated here:

https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/generator/src/generate-records.js#L79-L85

Support that argument in the generated Elm code here:

https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/generator/src/elm-file-constants.js#L78-L80

And change the type definition and `build` function here to support that data and store it:

https://github.com/dillonkearns/elm-pages/blob/14518e249716294994a875368fe2d3b09a1f3c89/src/Pages/PagePath.elm#L166-L170

Because we're supporting external image urls as well, and we don't download them as part of the build step, we won't have access to the dimensions for external images. So as a first pass, we'd probably make it a `Maybe` and not provide the dimensions if the image is external.

Happy to give guidance and help to anybody who is interested in picking this up! 😄

**Comment by Y0hy0h** [comment]
I might have a go at it. Just gathering some more pointers to places of interest in this comment.

I think you confused `ImagePath` with `PagePath` in the links above. :)

Following your advice, I would try out whether we can
1. Use sharp to extract the image dimensions here:
    https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/generator/src/generate-records.js#L105-L138
    (It also looks, like we could merge those functions, as they seem duplicated.)
2. Adapt this part to accept the image dimensions:
    https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/generator/src/elm-file-constants.js#L73-L75
3. Adapt the constructor at:
    https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/src/Pages/ImagePath.elm#L98-L100
4. Store the dimensions in:
    https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/src/Pages/ImagePath.elm#L98-L100
5. Add some accessor functions (that return `Maybe Dimensions`) to:
    https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/src/Pages/ImagePath.elm#L1-L4

**Comment by Y0hy0h** [comment]
@dillonkearns I'm running into trouble with sharp because it only seems to provide async functions. If we use that, as far as I understand, we would need to convert many functions in `
elm-pages/generator/src/generate-records.js` and its call site in `elm-pages/generator/src/plugin-generate-elm-pages-build.js` to be async as well.

Is there something I missed? Or should I just convert all necessary functions to async (and by the way also check if https://github.com/dillonkearns/elm-pages/blob/2446458ddaa1b49b5487e54d7f8a57beca8cad91/generator/src/generate-records.js#L109 can be made async)?

**Comment by dillonkearns** [comment]
Hey Johannes, great point. I didn't realize they were async, but that would involve changing it in a few places.

From what I understand, the NodeJS sync operations are actually faster than the async ones, so there's no reason to use the async ones if you're able to process things sequentially.

So it's okay to leave those operations as synchronous. But what will have to change the top-level for the plugin will need to be asynchronous. I just made this commit on master that I think should take care of that: https://github.com/dillonkearns/elm-pages/commit/1684c45ca3976bc5621f08f455840f5270841e92

**Comment by dillonkearns** [comment]
This function returns a Promise already: https://github.com/dillonkearns/elm-pages/blob/1684c45ca3976bc5621f08f455840f5270841e92/generator/src/generate-elm-stuff.js#L10
