### ISSUE TITLE
Direct links to image lead to routing error

### ISSUE THREAD

**Issue by Y0hy0h** [dillonkearns/elm-pages#105]
I've tried adding links to image's source, so that people can open them full screen if they want to. Unfortunately, when the image is clicked, it reports `Page not found. Valid routes: , blog, blog/draft, blog/hello`

If I open the link in a new tab, it loads fine, because the error is with elm-pages interception of a link click. I'm not sure exactly what is wrong, but there is definitely the assumptions that such links point to pages, and not directly to images like in this case.

## Reproduction
1. In the [elm-pages-starter](https://github.com/dillonkearns/elm-pages-starter), replace the last definition in `src/Page/Article.elm` with the following.
    ```elm
    articleImageView : ImagePath Pages.PathKey -> Element msg
    articleImageView articleImage =
        Element.link []
            { url = ImagePath.toString articleImage
            , label =
                Element.image [ Element.width Element.fill ]
                    { src = ImagePath.toString articleImage
                    , description = "Article cover photo"
                    }
            }
    ```
2. Run `npm run start` (or `npm run serve`), go to http://localhost:3000/blog/hello and click on the image of the book. It should show the error.
3. Now select the url bar and press enter to trigger a new request. It should load the image.
4. You can play around with pressing the browser's back and forward button and clicking on the image.

**Comment by tennety** [comment]
I thought this was already fixed before 🤔 Just for reference, in case it helps with any regressions: https://github.com/dillonkearns/elm-pages/issues/17

**Comment by kyasu1** [comment]
I have also encountered with this problem and here are my thoughts.

The easiest work around is just open the image in another tab by using `newTabLink`, this works as expected. Because all links are once routed to the internal update function as normal Elm app, it is possible to support the behavior as you mentioned if we add another condition to hard reload the page at the following code if the target link is images.

https://github.com/dillonkearns/elm-pages/blob/007c9c823f2ec1e7ef65c4b646b3ebb8030c5cb5/src/Pages/Internal/Platform.elm#L494-L510

But I think the Elm way is creating a page dedicated to display images, so we can keep the app state and navigate pages without loosing user experiences.

**Comment by Y0hy0h** [comment]
In the new version, opening images on the dev server works as expected.

**Comment by dillonkearns** [comment]
Thank you for trying it out on the latest version, I was just wondering about this 🙏
