### ISSUE TITLE
unfortunate install experience

### ISSUE THREAD

**Issue by youlam** [dillonkearns/elm-pages#113]
So running

`git clone git@github.com:dillonkearns/elm-pages-starter.git`

got me this error:

```
Cloning into 'elm-pages-starter'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Next, not knowing any better, I manually downloaded `elm-pages-starter-master.zip` to my machine, unpacked it to a directory, and then went in there and ran `npm install`. To my great consternation (I don't know any better I'm a newbie), this did stuff like re-download Elm 0.19.1, which I already had on my machine, and re-downloaded a bunch of other stuff like `elm-format` and `puppeteer` that I already had on my machine, and plunked it all into the `node_modules` folder. (I guess.)

As a beginner, can I please ask, what's a way to avoid this duplication of packages across different  `node_module` folders? Should I have run `npm install -g`, or what?

PS: After running `npm start` it did another bunch of downloads, declared success, and I still have no idea how to use the thing (where do I see the served pages or the rendered assets? what's going on inside `Index.js`? huh?)

**Comment by dillonkearns** [comment]
Hello @youlam, the `Permission denied (publickey)` error you're talking about sounds like an issue with cloning the repository in a way that isn't working for GitHub, it's not specific to this tool. You'll have to do some Googling there, but I'm guessing it might have to do with cloning with https vs. ssh. For a public repo, it seems to work better if you clone with https. Otherwise, it tries to check if you have permission when you clone it. This article has some info on how to clone using https: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository.

> As a beginner, can I please ask, what's a way to avoid this duplication of packages across different node_module folders? Should I have run npm install -g, or what?

Unfortunately, this is just a limitation in the way that NPM works. You can do some Googling there as well to look for other solutions, but I haven't tried any of them. Most people just accept re-downloading things over and over, as strange as that sounds. I don't recommend trying `npm install -g` as it is likely to cause problems, and it won't stay in sync as a project's dependencies change.

Elm installs its own dependencies in a way that can be cached across your whole system, which is great.

Regarding the `index.js` file, it might be a lot of concepts to take in at once. This is still a project that is iterating and changing rapidly at this point, and the structure of that isn't documented thoroughly yet. The best place to get more help on that is in the #elm-pages channel in [the elm slack](https://elmlang.herokuapp.com/). In a nutshell, `index.js` is the place that you can import any CSS or JS assets to include them in your bundle. `Main.elm` is the entrypoint for your Elm code for your elm-pages app.

Feel free to ask more followup questions in the #elm-pages channel in the Elm slack, we'd be happy to help out more there.

**Comment by Erudition** [comment]
I had the same experience.
It seems weird that you gave the git-based cloning URL for the starter app since that won't work for most people. I had to go to the repo and find the https version of the command:
`https://github.com/dillonkearns/elm-pages-starter.git`

And I'm having the same problem figuring out where the site is served from. I see a million things pointing to a `/dist` folder, but I don't have one - even after running `build`. I even created the folder manually, and no matter what I do it stays empty. Where am I supposed to point e.g.  GitLab Pages or Github Pages for hosting the final HTML?

I've read everything I can find on elm-pages online, which was not much, and there's no mention of the `dist` folder, nor is it in any of the repositories.
