### ISSUE TITLE
Difficulties including font files

### ISSUE THREAD

**Issue by Y0hy0h** [dillonkearns/elm-pages#134]
When trying to self-host font files, there are difficulties.

`woff` and `woff2` file extensions are not pre-configured for webpack, so it fails to parse them. (See https://github.com/dillonkearns/elm-pages/pull/129.)

I think there is also a problem with the url resolution as follows: Assume a `style.css` in the root folder. Then the fonts go in `static/fonts`. But the final URL which points to the fonts is `fonts/font-file.woff`, not `static/fonts/font-file.woff`. So the URL resolution fails. (Note that I did not reproduce this, this is from my recollection of my problems.)

A workaround is to disable URL resolution for the CSS file, as described in https://github.com/dillonkearns/elm-pages/pull/129#issuecomment-660681701.

**Comment by dillonkearns** [comment]
Hello! elm-pages is now moving away from webpack completely, see my comment about font loading here: https://github.com/dillonkearns/elm-pages/issues/94#issuecomment-717375941.

I'll close this issue since I think the new no-bundling approach will allow you to do font loading from font assets in the `static/` folder now. But if there are any issues or concerns there, please chime in to the discussion at #148. Thank you!
