### ISSUE TITLE
Service worker caching not working?

### ISSUE THREAD

**Issue by bhansconnect** [dillonkearns/elm-pages#135]
I just learned of this library, and have been messing around with it. I have been using the starter site, but it does not seem to be loading the shell of the web page when offline. In lighthouse, the site is installable, but it doesn't return 200 when offline.

[elm-pages.com](https://elm-pages.com/) also doesn't load anything when offline. Surprisingly, [brianginsburg.com](https://brianginsburg.com/), which is a showcase site, does load when offline. Maybe it is using an older version and thist is a regression? Is there extra configuration that is necessary to make a site load offline that I am missing, or is this broken in the framework related to this?

**Comment by dillonkearns** [comment]
Hello!

Yes, you're absolutely correct. An older version of elm-pages did use the service worker to make the landing page available when offline. And most of the service worker functionality was removed in https://github.com/dillonkearns/elm-pages/commit/dd964fe2df9146284b5879eff844c3f4b155f457 because it was causing some issues.

I do think that `elm-pages` can provide a nice experience for service workers, and it's a goal of mine. But it's difficult to get right, and I think that users will need some control over the caching strategies. My vision is to have an API like this eventually to let users say what to cache and how: https://github.com/dillonkearns/elm-pages/issues/57.

I will also need to revisit some trickier parts of that process when I get there. For example, if you have a certain page cached, and you load a new page that depends on a newer version, the page will need to do a full reload to make sure everything is in sync. So I'll need to send a hash that shows what version of the bundled JS is compatible with the content.json.

I'll close this issue for now since I'm tracking it with #57. But feel free to continue the discussion there, I'd love to discuss it more!
