### ISSUE TITLE
Line breaks (double space or \ or <br />) appear to be non-functional

### ISSUE THREAD

**Issue by confusingbits** [dillonkearns/elm-pages#141]
None of these methods appear to work to add line breaks from the markdown file in development at least.

edit: This appears to be an issue with CRLF vs LF line endings.

**Comment by dillonkearns** [comment]
Hello @confusingbits. I'm guessing you're using the `elm-pages-starter` repo? That template uses `dillonkearns/elm-markdown` under the hood.

It does look like [the line ending in the markdown spec](https://github.github.com/gfm/#line-ending) allows for U+000A, U+000D, or U+000D followed by U+000A. But perhaps we only check for regular newlines?

Could you file an issue in [the `dillonkearns/elm-markdown` repo](https://github.com/dillonkearns/elm-markdown)?

And regarding the `<br />` tags, HTML is only allowed as explicitly listed in the html parser when you setup the parser. So that's worth mentioning as well, that might be something that could be made more clear in the documentation.

Thanks for reporting the issue!

**Comment by confusingbits** [comment]
Thanks. I opened the issue on elm-markdown as suggested. :)
https://github.com/dillonkearns/elm-markdown/issues/55

**Comment by dillonkearns** [comment]
Perfect, thank you!
