### ISSUE TITLE
Language-Support (<html lang="..." />)

### ISSUE THREAD

**Issue by ni-ko-o-kin** [dillonkearns/elm-pages#157]
Hi!
How do I add another lang than en. I found elm-pages/7.0.0/src/Pages/Manifest.elm at line 77 `type alias Language =` but I don't know where to set it.

Some users have enabled automatic translation in their browser. So the elm-pages generated site gets translated incorrectly because the lang is set to en-US.

If this is not supported for now I would appreciate a workaround because I have finished a site and I want to go online with it aso.

Best regards,
Nikolaus Wettstein

**Comment by dillonkearns** [comment]
Hello!

I think running a shell command like this would work as a workaround:

```shell
find dist/ -type f -exec sed 's/lang="en"/lang="<your-language-code>"/g' {} \;
```

You may also be able to set `<div lang=<your-language-code>...` in your top-level HTML element and get the same effect without running any scripts on the build output. So that's probably worth a try first.

Note that browser plugins and tools that change DOM nodes can cause issues with Elm apps. There's was a Slack thread recently with a workaround for Google Translate in Elm apps that might be relevant: https://elmlang.slack.com/archives/C0CJ3SBBM/p1610750388057300 (here's the copy-pasted text in case Slack archives it https://gist.github.com/dillonkearns/e495ce6f6d36a5524e4b5d08edb629d4).

## Longer Term Solution

Longer-term, I think it makes sense to add `Head.lang`. I've thought about this design in the past, and the main reason I haven't added it yet is because I'm debating whether it should just take a `String` argument, and leave it to the user to make sure they pass in a [conformant language code value](https://en.wikipedia.org/wiki/IETF_language_tag). Or whether I should leverage a more type-safe API for that.

For reference, here are the docs for the `lang` tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang.

There's always a balance between type-safety vs. complication in cases like this. Depending on how often values in the standard change, how it impacts the usability of the API, how complex the type-safe version is, etc., it can sometimes be better to go with a String.

There could be some middle ground for an API as well. For example, having a fallback constructor takes the pressure off from having to include every valid language, but can give some added confidence for the cases that it explicitly handles. This is much like the pattern that is used in `elm/html`.

```module
module Language exposing (Language, en, es, zh, {-etc.}, custom)

type Language = Language String

en = Language "en"

es = Language "es"

custom = Language
```

There are also subtags (see https://en.wikipedia.org/wiki/IETF_language_tag). So the API could potentially provide a way to include subtags as separate values, then join them with "-". Or that case of needing subtags could just be handled by the `custom` constructor.

99% of the time users will probably just be using a small standard set of language codes without any subtags. So we could probably get a simple API that's useful for those cases without the added complexity using that approach.

**Comment by dillonkearns** [comment]
I started working on a package for the language tags here: https://github.com/dillonkearns/elm-bcp47-language-tag. That could be used for the `elm-pages` API. Something like `Head.lang : LanguageTag -> Head.Tag pagePath`.

**Comment by dillonkearns** [comment]
And here are the package docs for this unpublished package: https://elm-doc-preview.netlify.app/?repo=dillonkearns/elm-bcp47-language-tag&version=main (they'll be on the package site once it's initially published).

**Comment by ni-ko-o-kin** [comment]
I tried the <div lang="...." approach but it did not work. I will try the script/sed method as well. But a dedicated package would be very nice to have! Thank you for your great response!

**Comment by ni-ko-o-kin** [comment]
Changing the lang tag after the build with sed did work. :)

The newly created [bcp47 package](https://package.elm-lang.org/packages/dillonkearns/elm-bcp47-language-tag/latest/) cannot be used with elm pages yet, right?

Thank you for your efforts!

**Comment by dillonkearns** [comment]
This is now part of the latest elm-pages! Hope this works well for your use case 😄
