### ISSUE TITLE
Files aren't generated for extensions besides .md and .emu

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-pages#16]
The problem is that currently the extension is hardcoded for `.md` files here:

https://github.com/dillonkearns/elm-pages/blob/eb5b7b7eb20c061c8727ae13666e5007da0c1166/generator/src/elm-pages.js#L46-L65

`.emu` files need special treatment so they can remain separate. Removing the hardcoded `.md` extension should fix the problem.

**Comment by dbj** [comment]
This is really holding me back. I need to be able to parse different types of files. I'm using dillonkearns/elm-markdown and it does not parse HTML.  I tried defining my own htmlDocument and it does not work:

```elm
main =
    Pages.application
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        , documents = [ markdownDocument, htmlDocument ]
        , head = head
        , manifest = manifest
        , canonicalSiteUrl = canonicalSiteUrl
        }

htmlDocument =
    let
        res =
            \md ->
                case HP.run md of
                    Ok hp_nodes ->
                        Ok (H.div [] (HPU.toVirtualDom hp_nodes))

                    Err deadends ->
                        Ok (H.text (Parser.deadEndsToString deadends))
    in
    Pages.Document.parser
        { extension = "html"
        , metadata = Metadata.decoder
        , body = res
        }
```

**Comment by dbj** [comment]
Of course! :)

And congrats!!! Definitely worry about the wedding and (hopefully) honeymoon first.

I just wanted you to know I’m using it for a critical project (accepting the risks, of course) so you could prioritize amongst other things.

I’m looking forward to your new feature, which, I think, is the ability to bring in data from an external source (say through GraphQL), which is also an important feature for my long-term plans.

No worries. Thanks for all you do to contribute to the Elm ecosystem.  I also love to read your code - I’ve learned a lot.

Dirk


"You cannot legislate the poor into prosperity by legislating the wealthy out of prosperity. What one person receives without working for, another person must work for without receiving. The government cannot give to anybody anything that the government does not first take from somebody else. When half of the people get the idea that they do not have to work because the other half is going to take care of them, and when the other half gets the idea that it does no good to work because somebody else is going to get what they work for, that my dear friend, is the beginning of the end of any nation. You cannot multiply wealth by dividing it.”
Adrian Rogers, 1931

**Comment by dillonkearns** [comment]
Thanks for understanding! I'm excited to hear that you're using it for your project, and definitely want to make it work for your needs!

And yeah, that's right I'm working on the StaticHttp functionality right now, which is actually getting pretty close to production-ready! Here's some (already working!) code to give you a sense of what it will look like:

https://github.com/dillonkearns/elm-pages/blob/4023bf8be523d6b7a5d8b1cfbe946521c25132ca/examples/external-data/src/Main.elm#L119-L179

I'm actually getting some help in a sort of closed beta round right now on it, and it's working really nicely. It skips GraphQL entirely, which I love because it reduces the number of extra abstractions... you just directly ask for the data in your Elm code, and it grabs it in the build step! I'm working on `StaticHttp.andThen` right now, which will allow for some really interesting possibilities. As you may have seen, I'm tracking that at https://github.com/dillonkearns/elm-pages/projects/1.

Thanks for your interest in the project! I appreciate the feedback, please keep it coming. I'll do my best to get out some of these features and fixes before I head out for the wedding 😄

**Comment by dbj** [comment]
Nice!  I love Airtable and was definitely going to be using it for one of my sources.

**Comment by dillonkearns** [comment]
This is published now 👍  Be sure to update both the NPM and Elm packages to get the fix.

https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#1040---2019-11-04

https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-ELM.md#101---2019-11-04
