### ISSUE TITLE
Static asset routes not recognized

### ISSUE THREAD

**Issue by tennety** [dillonkearns/elm-pages#17]
When I try to open an image rendered within a post/page in a new tab, I get the `Page not found` error, saying the url is not a valid route. To reproduce:

* Navigate to https://elm-pages.com/images/article-covers/extensible-markdown-parsing.jpg

**Expected:**
The image shows in the browser
**Actual:**
Page not found error
EDIT:
Hard-refreshing the image url does show the image.

~I wonder if [this line](https://github.com/dillonkearns/elm-pages/blob/9d0e855a2d2089039be9c119fadcdfa115cb057b/generator/src/elm-file-constants.js#L25) should also include `allImages` in the list of routes.~
Per conversation with @dillonkearns it seems like it could be related to the service worker fallback url.

**Comment by dillonkearns** [comment]
@tennety I added a regex to check for files containing a dot (so anything with an extension), and it doesn't use the service worker cache to try to serve up the HTML shell for those pages.

https://github.com/dillonkearns/elm-pages/blob/a0a99dab5280e759d408bf4f0e5f831efd090f16/generator/src/service-worker-template.js#L7

So that solves it for images and other files with extensions. It's still not a full solution, but it solves a lot of the most common cases for now. Hope that helps!
