### ISSUE TITLE
Elm-markup files not parsed succesfully

### ISSUE THREAD

**Issue by antoine-atmire** [dillonkearns/elm-pages#20]
I have a basic `content/elm-markup.emu` file  which works with 1.0.39 (npm) and 1.0.0 (elm) but which cannot be rendered with elm-pages 1.0.40 (npm) and 1.0.1 (elm)

The page shows up like this
```
/elm-markup
I couldn't parse the frontmatter in this page. I ran into this error with your JSON decoder:
Failure
```

**Comment by dillonkearns** [comment]
I released a fix for this: https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#1041---2019-11-14

Could you try it out and let me know if it's looking good now? Thank you!

**Comment by antoine-atmire** [comment]
/elm-markup is a blank and unresponsive page now, while all other pages render properly.

**Comment by dillonkearns** [comment]
Hello @antoine-atmire! I'm not sure if you're still using `elm-markup` with `elm-pages`. If you are, could you take a look and let me know how things work with the latest version using `elm-markup`?

I've removed the coupling to `elm-markup`, so the way to do it now is to store the `elm-markup` metadata in a field in your frontmatter (instead of it being raw `elm-markup` directly in the frontmatter of the file).

**Comment by dillonkearns** [comment]
I believe this is fixed, so I'll close this for now. Please let me know if you run into any other problems. Thank you!
