### ISSUE TITLE
Content file names can't start with a digit

### ISSUE THREAD

**Issue by antoine-atmire** [dillonkearns/elm-pages#21]
E.g. `content/001.txt` won't compile

It produces this elm error message
```
-- PROBLEM IN RECORD ------------------------------------------------- Pages.elm

I just started parsing a record, but I got stuck here:

89|     { 001 = (buildPage [ "001" ])
          ^
I was expecting to see a record field defined next, so I am looking for a name
like userName or plantHeight.

Note: Field names must start with a lower-case letter. After that, you can use
any sequence of letters, numbers, and underscores.
```

Sure enough in gen/Pages.elm it's using the filename as a record's field name. 
```
pages =
    { 001 = (buildPage [ "001" ])
    ,  ...
```

I noticed that dashes in the file names are sanitized here. I suppose something similar could be done.

**Comment by Ball** [comment]
This also happens with directories.  This prevents permalinks from being maintained for a wordpress migration

**Comment by antoine-atmire** [comment]
Similarly file names with multiple extensions e.g. `content/file.json.txt` also cause problems because of the dot.

**Comment by dillonkearns** [comment]
Hello @antoine-atmire and @Ball, thanks for the feedback! This one will require a little design thinking. There are several directions this could go, all of them with pros and cons.

## Some possible normalization strategies

### Common prefix
Start with a common prefix for all pages. For example:

`content/001.txt` => `Pages.page001`
`content/blog/hello.md` => `Pages.pageHello`


### Only prefix when invalid

`content/001.txt` => `Pages.page001`
`content/blog/hello.md` => `Pages.hello`

## Multiple file extensions

@antoine-atmire what would be the reason for having a file with multiple file extensions in an `elm-pages` site? Could you elaborate on the use case there?

## Next steps

Those are just a couple of ideas to get the conversation going. It's also worth noting that different normalization rules have different implications for collisions (because the different strategies result in some files with differing names normalizing to the same record field name).

Let's try to collect a list of different concrete examples representing these different use cases, discuss some different strategies, and list out what the files would normalize to as above. Then we can write some tests and handle that normalization fairly easily. The hard part is coming up with the right normalization strategy.

**Comment by antoine-atmire** [comment]
To elaborate on the multiple extensions, for a personal project that I mentioned [here](https://github.com/dillonkearns/elm-pages/issues/26) I would like to render code as my content. For example I would like example.com/project/files/package.json to show the content of package.json. These files sometimes have multiple extensions. I also don't want to make a parser for each possible extension a code file could have so my idea was to rename the files and add a '.file' extension to all of them. 
Note this personal project is just my way of getting familiar with elm-pages. It's not a priority in any way.

**Comment by icidasset** [comment]
A common prefix makes the most sense to me. Maybe we could use the file extension as a prefix?
```elm
pages.txt_001
pages.md_hello
```

Regarding "Multiple file extensions", I had the idea to use both a yaml file and a markdown file for the same page. Where the markdown would be the biggest piece of content and then the yaml file would be used for additional bits of text (like labels and what not).

**Comment by dillonkearns** [comment]
Hey @icidasset, quick note on this point:

> Regarding "Multiple file extensions", I had the idea to use both a yaml file and a markdown file for the same page. Where the markdown would be the biggest piece of content and then the yaml file would be used for additional bits of text (like labels and what not).

The `elm-pages` CLI uses [`gray-matter`](https://www.npmjs.com/package/gray-matter) to parse the frontmatter (i.e. the stuff between the `---`s at the top of your files in the `content` folder). Out of the box, `gray-matter` will parse either YAML or JSON. When you define your metadata parser in Elm, it is first turned into the corresponding JSON (even if it's YAML). But you can already have YAML in your markdown files 😄

**Comment by dillonkearns** [comment]
Regarding the file extension as a prefix: that doesn't feel quite right at first glance because the routes don't include the file paths, and so that seems like a low-level detail that you shouldn't need to know when you're referring to a route.

I think it would make more sense to just have a single prefix for everything. Something like:

```
pages.route_001
pages.route_hello
```

But that also feels unfortunate because then you have to pay a penalty, even if all of your routes are valid Elm record field names. Although, it's also not ideal if you get used to being able to use the name without any prefix, but then for those special cases you have to remember to use the prefix... so it's either consistently inconvenient, or inconsistent 😒 No easy solution here! 😅

**Comment by icidasset** [comment]
> Out of the box, gray-matter will parse either YAML or JSON.

Oh, that's cool, I was wondering why this worked out of the box 😄 But what I actually was talking about, was that the entire file would be yaml, without any frontmatter.

> so it's either consistently inconvenient, or inconsistent 😒 No easy solution here! 😅

Yeah true. Too bad that this is a limitation of Elm 🤷‍♂ I guess in that case I'll vote for "consistently inconvenient" 👍

**Comment by dillonkearns** [comment]
@icidasset I think you have all the tools to parse the entire file as YAML as well! You can pass your own parser and define your own extensions. So you could define a parser for YAML using https://package.elm-lang.org/packages/dillonkearns/elm-pages/latest/Pages-Document#parser and something like Tereza's YAML parser (note that it's an incomplete parser, but worth trying it out: https://package.elm-lang.org/packages/terezka/yaml/latest/).

For the sake of keeping this thread easy to follow, could you let me know how that goes in either Slack, or a fresh Github issue? Great to hear your use cases, that's really helpful! 😄

**Comment by kyasu1** [comment]
So far `elm-pages` is working greatly including Netlify CMS integration. Great ! I have been using Go Hugo but I was always thinking if I could write their logics in Elm. Just Go is not my favorite 😝. Anyway I think this issue is one of the main obstacle for moving from another blog systems. This just my naive idea but it is possible to implement I think.

How about representing record field names with encoded strings something like Base58 which only contains alpha numerics ? The following is an example, a prefix character 'b' is added to avoid errors in case of the encoded string with digit. 

```
type pages =
    { b6M4uDp2 = (buildPage ["blog"])) -- Base58 encoded /blog
    , b3uzqYXfA4pnsTNPsY9GppLNZxJyZy = (buildPage ["blog", "test-2020-02-20"] -- Base58 encoded /blog/test-2020-02-20
    }
```    

The reason

1. I think it is almost impossible to represent all filenames as Elm record fields. Not only starting digit but spaces, special characters etc. will also cause error. And it is impractical to force ordinary users to upload files with elm friendly filenames.
2. Yes the field names are not human friendly. However I often need to open `Pages.elm` and check the actual field name in the current implementation. I can remember the rules such as `-` is mapped to CamelCase and `_` is not changed etc, but if you add more rules I am not sure if I could remember all of them !

Since this is a breaking change, adding a command line option to choose which naming scheme is possible.

Thanks !

**Comment by dillonkearns** [comment]
Hello @kyasu1! Thank you for sharing your ideas, it's great to have more input for the discussion!

> Yes the field names are not human friendly. However I often need to open Pages.elm and check the actual field name in the current implementation. I can remember the rules such as - is mapped to CamelCase and _ is not changed etc, but if you add more rules I am not sure if I could remember all of them !

The goal of having that handy record syntax is to make it user-friendly and easy to use. I'd like to keep it that way for paths that allow us to go down a happy path. This does introduce a lot of challenges, and indeed not only do we have to normalize certain names, but there's a possibility of collisions and so we have to think about cases where multiple names normalize to the same thing.

One possibility could be to give users a way to provide their own rules. Another possibility could be to have a common prefix that allows us to have names starting with numbers. It's a really tricky question!

It does kind of seem like it might make sense to have it be application-specific, because some apps may have, for example, unicode characters, or lots of ambiguous characters that normalize to the same thing with a specific strategy. So if we make that extensible, then it allows most users to use the default strategy, but people with very specialized use cases could find a strategy that works for their needs.

Regardless, we'll want a good default strategy, so let's try to pick one that supports common cases like having numbers in routes for now and go from there.

**Comment by Erudition** [comment]
I think I can solve the consistency problem.

- If there are no initial digits, use the same name we use now.

- If there are some initial digits, 
    - remove them, and add that to the record,
    - but also, add a copy to the record with the numbers intact and a simple `_` prefix!

`2021-01-17-welcome-to-my-blog` -> `pages.welcome-to-my-blog` AND `pages._2021-01-17-welcome-to-my-blog`.

No heavy prefix. No required prefix! No bespoke rules. Backwards compatible! No loss of convenience. Maintains order.

**Comment by dillonkearns** [comment]
Unfortunately field names can't start with `_`'s. So it would have to be something like `n_`.

But I think `n_ 001` is probably reasonable. It's tricky because there's no perfect solution, there can always be collisions. You could have multiple routes that normalize to the same name. But it's one of those cases where you just pick a heuristic and go with it 🤷‍♂️

**Comment by dillonkearns** [comment]
The `Pages.pages` record is no longer generated in the 2.0.0 NPM package/8.0.0 Elm package. The new version generates a `Route` module, which gives you type-safety that guarantees you're referring to a valid route. In the future, I'm hoping to add an integration to help consume `DataSource` values from `elm-review`, so that users can define rules to help validate that programmatically referring to routes can be done without any mistakes.

This issue is no longer happening in the new version, so you can use any set of numbers, underscores, etc. within route segments 👍
