### ISSUE TITLE
`elm-pages build --base sub` does not render correctly

### ISSUE THREAD

**Issue by j-maas** [dillonkearns/elm-pages#217]
The dev server strips the base properly. But when I try to build, the index is rendered into a subfolder and contains a rendered error message about it being an invalid route. See this [test HTML output for an index file](https://github.com/dillonkearns/elm-pages/pull/237/files#diff-a07fa31cd40645630c26c5ab3a1acc95711cb0b608a4d91c6a75ec5689cd8634R28) for an example.

# Reproduction
1. Check out https://github.com/Y0hy0h/unnecessarily-bad-design/tree/e93e004dcd3cfdc81cf67a1eb23c01d1a095ea38. (I currently don't have a simpler elm-pages repo. The `./examples` don't build for me.)
2. `npm install`
3. `npm build -- --base sub`
4. Look into `./dist`. There is a `./dist/sub/index.html` that says "Page Not Found".

**Comment by Y0hy0h** [comment]
I discovered that this because `Route.toPath` converts the Pages.Index to `/sub/`, but that is put into `Path.fromString` which chops the trailing slash, leaving `/sub`.

I assume there is some code somewhere that removes the base path from these paths, but since the base path is `/sub/` with a trailing slash, it does not affect `/sub` which is left to be wrong.
