### ISSUE TITLE
unused `elm-pages.js` file in the dist folder

### ISSUE THREAD

**Issue by megapctr** [dillonkearns/elm-pages#219]
After running `elm-pages build`, there is an `elm-pages.js` file in the dist folder that is not linked anywhere. It's safe to delete it, but maybe there is a bug and it was supposed to be loaded somewhere in the generated html?

**Comment by dillonkearns** [comment]
Oh yes, so I think I used to import `elm-pages.js` into each page. Then I was analyzing the performance with Lighthouse and noticed an unnecessary level in the dependency requests waterfall, and since it's such a small script I could minify that and include it as an inline script. Turned out to be a win for performance.

I need to get it fully automated to take that `elm-pages.js` script, minify it, and include that minified snippet in the HTML source. But you're absolutely right, that file doesn't do anything in the `dist/` folder and shouldn't be copied in there anymore 👍 Thanks for reporting the issue!
