### ISSUE TITLE
Search page inside elm-pages

### ISSUE THREAD

**Issue by JohanWinther** [dillonkearns/elm-pages#250]
Hello! 👋

I am interested in elm-pages, but I haven't really seen a way to do search when you have a search API based on e.g. Elasticsearch.
Of course it is impossible to pre-render all possible queries during compile time, so I'm wondering if there are any solutions that won't require you serve up your search page outside of elm-pages.

**Comment by dillonkearns** [comment]
Hey there @JohanWinther 👋

`elm-pages` hydrates into a full-fledged Elm SPA (single-page app). That's good news for your use case, because it means you can wire in a fully dynamic search UI to your application! The way you do that is just like in a vanilla Elm application. You can add global dynamic `Msg`s in `Shared.elm`, or you can add it in an individual Page Module by changing `Page.prerender` to `Page.buildWithLocalState`. I hope that helps! You're welcome to ask more questions any time in the `#elm-pages` channel in [the Elm Slack](https://elmlang.herokuapp.com/), or in the [Discussions section of this repo](https://github.com/dillonkearns/elm-pages/discussions).

**Comment by JohanWinther** [comment]
Thank you for your quick reply! In hindsight I should have read the docs more thoroughly.
I will make sure to post in the discussion section next time!
