### ISSUE TITLE
Image optimization API

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-pages#36]
I’ve been thinking about image optimization. My longer-term vision is to have fine-grained control over the image optimization (rather than a single rule for all images). I’m imagining an API similar to the StaticHttp design. So you could do something like this:

```elm
OptimizedImage.srcset { includeWebp: True, defaultFormat: OptimizedImage.jpeg, widths = [ 2000, 1200, 500 ] } Pages.images.hero
```

That’s just totally a back-of-the-envelope sketch, but the idea is that, like `StaticHttp`, this would be something that has multiple stages:

*Build stage*
elm-pages goes through and turns all of the OptimizedImage calls into actual optimized images (exactly analagous to the lifecycle of StaticHttp fetching all the static http content).

*Runtime stage*
It simply refers to the built image by filename, where the filename is generated based on the minification options and filename.

Similar to the StaticHttp, OptimizedImage would be something you would chain and get the data back in the view function, see: https://elm-pages.com/blog/static-http/#let'sseesomecode!

And it would give you something you could use directly to create a srcset (which if you haven’t heard of it, it’s a very cool browser API that allows you to progressively enhance your page with performant images that download the right dimensions based on the device you’re using).

## Prior Art
For reference, here are the docs for Gatsby’s image optimization https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/

In the case of Gatsby, it’s done through GraphQL fragments. With elm-pages, this StaticHttp pattern of getting data is the equivalent of Gatsby’s GraphQL layer. It will probably evolve over time, but IMO it’s a lot simpler and more type-safe doing it without the extra layer of abstraction of using GraphQL 😄 

## Responsive Image reference material
Getting to the low-level details of how to build the actual HTML for the responsive images, here are some handy resources:

https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

I think that the `elm-pages` API for responsive images should give you a function that turns the value into actual HTML directly. When using something like `elm-ui`, there is no high-level API for srcsets, and even if there was there is more that can go wrong if you give the user the list of paths to the image resources and their metadata instead of directly giving the proper HTML for the responsive image. So unless there's a good reason not to, I think that's the ideal design.

**Comment by Wolfsun** [comment]
Some extra thoughts on this, not sure if helpful or not? :-)

Some example output from gatsby below.Using the img tag with srcset and sizes for resolution switching but also using the picture tag, source tag with srcset and sizes for art direction. 

For reference https://www.gatsbyjs.org/packages/gatsby-image/
And for art direction https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images

```
<picture>
	<source 
		srcset="/static/ae041/tray.jpg 79w,
				/static/aeffe/tray.jpg 158w,
				/static/13777/tray.jpg 316w,
				/static/36f83/tray.jpg 474w,
				/static/334eb/tray.jpg 632w,
				/static/8fa1d/tray.jpg 1329w" 
		sizes="(max-width: 316px) 100vw, 316px"
	>
	<img 
                sizes="(max-width: 316px) 100vw, 316px" 
		srcset="/static/ae041/tray.jpg 79w,
				/static/aeffe/tray.jpg 158w,
				/static/13777/tray.jpg 316w,
				/static/36f83/tray.jpg 474w,
				/static/334eb/tray.jpg 632w,
				/static/8fa1d/tray.jpg 1329w" 
		src="/static/13777/tray.jpg" alt="" 
		loading="lazy" 
		style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 1; transition: opacity 500ms ease 0s;"
	>
</picture>

```

**Comment by asianfilm** [comment]
I wonder if different APIs for different backends makes sense, since some will be hosting images on Airtable, some in Cloudinary, etc, which have different URL renaming schemes for responsive images. 

If using Netlify to host the site, and Git LFS to communicate the images, this link has great information:
[CSS-TRICKS: Getting Netlify Large Media Going](https://css-tricks.com/getting-netlify-large-media-going/)

In the article, note the tip about the need to use [Netlify Credential Helper](https://github.com/netlify/netlify-credential-helper) and the final section about image resizing on-the-fly using `sizes` and `srset` in image tags.

From memory, I found Cloudinary significantly faster than Airtable for hosting images, but then one needs to add an additional build stage to update Cloudinary. (You can provide Cloudinary with the Airtable image URLs and then don't need to download images locally before uploading to Cloudinary.)

Note that Cloudinary recommends naming images after their MD5 hash to reduce duplication. And when uploading to Cloudinary, you can request a perceptual hash to further reduce duplication. (I use Elixir locally to calculate perceptual hashes and delete near-similar images from Airtable.)

I did experiment once with hosting all my website images on Netlify through Git LFS but can't remember how the speed was. Note that there's a 100GB bandwidth/month limit on the free Starter account.

**Comment by dillonkearns** [comment]
I've done some more thinking on this topic and I'm thinking more and more that image processing is best done as a separate process outside of the elm-pages build. I laid out some of these thoughts in #148.

I've been moving some image handling to Cloudinary, and it's resulted in far more performant builds, as well as more performant sites (it does a better job optimizing images than I think we could do in a build step).

But more important, users should get to decide what process to use to optimize images. If we build that in to elm-pages then we not only build in an opinion about image processing, but we add that bloat to the installation, even for those who may not want to use it.

I'd love to hear thoughts on this, so feel free to chime in if you have opinions, prior art on how other frameworks approach this, etc. I'll close this issue as I am currently not planning on building an image optimization API as part of the core elm-pages setup. At some point, I may consider having a way to do JS-interop with NodeJS during the elm-pages build, which might open up opportunities for people to build a way of doing this without it being a core built-in part of elm-pages. But for now, this is not on the roadmap.
