### ISSUE TITLE
Allow StaticHttp to make requests for something other than JSON

### ISSUE THREAD

**Issue by icidasset** [dillonkearns/elm-pages#46]
Currently elm-pages requires you to use JSON, I'd like to parse an RSS feed which uses XML. How do you feel about making this independent of JSON? I can help with this if you want me to.

**Comment by dillonkearns** [comment]
Hello @icidasset! Thanks for sharing your use case, that's really helpful.

The reason I only including JSON in the initial `StaticHttp` API is because of the unused field stripping functionality. I knew that use cases would come in for non-JSON, but I wanted to try it with just JSON first to see how much we could push the boundaries with that nice functionality for optimizing down the JSON that gets included in the build.

That functionality seems to be working quite nicely. I wanted to make that optimized JSON data the path of least resistance.

I think for XML, unless somebody wanted to take the time to build the equivalent of Ilias's JSON decoding library which strips out unused values, we would just need to keep the entire value in the response. In terms of the technical change, that's totally doable and I'd be happy to add that (I've got a lot of context in that code so it would be pretty easy for me to add).

My question to you is, do you think that the performance cost will be acceptable to have that entire XML feed be loaded in order to load the page? If you know what the URL is, it might be helpful to take a look at the URL, or some info about it like how large the XML file is.

Thanks again for the context on this!

**Comment by icidasset** [comment]
> The reason I only including JSON in the initial StaticHttp API is because of the unused field stripping functionality.

Oh interesting! That makes total sense. Yeah, it doesn't seem right to introduce this performance penalty. I'll close this, as it's only a minor problem, since most things use JSON anyway 👍 Thanks for the explanation!
