### ISSUE TITLE
Files is 'static' folder don't get copied to the dist folder in develop mode, only on build

### ISSUE THREAD

**Issue by Wolfsun** [dillonkearns/elm-pages#47]
Files is 'static' folder don't get copied to the dist folder in develop mode, only on build. Once copied by build they work with development mode.

**Comment by dillonkearns** [comment]
Hello @Wolfsun, thanks for opening the issue. I'm not able to reproduce the issue on my machine. Could you give me:

* Some context about your environment (OS, elm-pages version, browser), and
* Steps to reproduce the issue (including the name of the static file you're having trouble with)

Thank you!

**Comment by Wolfsun** [comment]
Hi, I've done some more testing and I think the issue is at my end. I couldn't get locally hosted web fonts to work. They only started working when the font files had been copied to the dist folder. Could have been a caching issue? But can now confirm that elm-pages is working as expected and I can't replicate the issue.

**Comment by dillonkearns** [comment]
Thanks for the update!

So a couple of things that are confusing right now:

I just spoke to someone else who was expecting that a `static` file in the folder `static/my-static-file.txt` would be accessible through the url `localhost:3000/static/my-static-file.txt` (or whatever port or prod url you're using). But there's no static prefix, so it's just `localhost:3000/my-static-file.txt`. (This is different than for `images`, since those show up under `localhost://3000/images/...`.

And also, the service worker can be confusing sometimes, although it shouldn't try to serve up assets through the service worker that have a file extension 🤔

Anyway, just putting a note there in case it's helpful to you or anyone else who may stumble upon this in the future 😄

Thanks for taking the time to share your feedback!

**Comment by Wolfsun** [comment]
I think that explains it. I tried to use `static` in the path originally, that didn't work, I must have tried to build the site to see if that helped, then changed the path to reflect the fact that there was no `static` in the path in the `dist` folder. It then worked. I think I just assumed that the file needed to be in the dist folder to work. So when files weren't copied from `static` to `dist` I assumed that was a bug because I assumed the file needed to be in `dist` to work.
