### ISSUE TITLE
Lazy loading compile time data

### ISSUE THREAD

**Issue by MattiaVerticchio** [dillonkearns/elm-pages#494]
Hi Dillon,

First off, I absolutely love working with elm-pages! It's been a game-changer for building my website, [wattene.it](https://wattene.it/), which helps people in Italy find the best electricity provider.

I'm using compile-time data resolution to keep my site updated daily with the latest lists of cities, providers, and energy offers. However, I've run into a performance snag.

Currently, as far as I understand the inner workings of elm-pages, all this data gets injected into the HTML `<head>`, which can make the initial page load a bit slow, especially with larger datasets.  I've been working around this by `elm-codegen`erating Elm lists with the data baked in, to load it after the first HTML render, but that's led to a rather hefty JavaScript bundle size. 😅

I was wondering if there's a way to leverage `BackendTasks` to resolve this data at compile time, but then lazy-load it as bytes instead of embedding it directly in the `<head>`? This would allow me to keep the data up-to-date while improving the initial load time and reducing the bundle size.

Any guidance or suggestions would be greatly appreciated!

If this is possible, it might be helpful to add some instructions on lazy loading data to the elm-pages documentation. I'd be happy to contribute to the docs if you think this would be a useful addition!

Thanks so much for your time and for creating such an awesome framework!

P.S. By any chance, have you had a look at the PR I submitted a while back regarding the form `SetField` Msg?

**Comment by dillonkearns** [comment]
My general rule of thumb has been that the `Route`'s `data` should be relatively slim in size since it is required to be there before the page is displayed at all (by the contract of the `Route`, where `data` is available directly, not wrapped in a `Maybe` or any possible loading or error states). So given that, my advice to people is usually to keep that data as minimal as possible, and for loading larger data sets to use different features.

The data is injected into `<head>` to ensure that it is there as soon as the page loads so that the page can be hydrated immediately. This is pretty standard for other JS frameworks like NextJS and Remix as well.

With a larger data set, I usually advise people to load the minimal data needed using their `Route`'s `data`, and then to use vanilla `elm/http` through `init`/`update` to incrementally load larger parts of the dataset.

> I was wondering if there's a way to leverage BackendTasks to resolve this data at compile time, but then lazy-load it as bytes instead of embedding it directly in the <head>?

You may have already arrived at this idea, but you can use `BackendTask` through API routes in `Api.elm`, or create some `elm-pages` scripts to resolve data, in order to build data at build time. This doesn't get serialized as Bytes, it would need to be sent as JSON, but as I mentioned the idea lazy loading is in conflict to some of the core concepts of the `Route`'s `data`.

**Comment by dillonkearns** [comment]
I think that covers the main question of the issue, so I'll close it for now. Happy to discuss ideas for the future, but I want to keep the issues lean so that the signal to noise ratio stays high. A GitHub Discussion would be a good place to brainstorm for something that doesn't have a concrete action item but is just exploring possibilities for the future, always happy to have threads like that.
