### ISSUE TITLE
YAML frontmatter decoder

### ISSUE THREAD

**Issue by monacoremo** [dillonkearns/elm-pages#67]
Many thanks for the great project, Dillon!

By my understanding, it should not be too difficult to plug e.g. https://package.elm-lang.org/packages/terezka/yaml/latest/ as a frontmatter decoder, which would allow for much cleaner frontmatter on each page. The only snag is that there is no fitting constructor for `Pages.Document.DocumentHandler` - `parse` expects a `Json` decoder.

Would that be an option that you'd be willing to add, e.g. with an additional `parserWithFrontmatter` that takes a `String -> Result String metadata` as an argument? Happy to provide a pull-request if you do!

**Comment by dillonkearns** [comment]
Hello @monacoremo,

Glad that you're enjoying the project!

Try changing the frontmatter in your project to YAML and I think you'll be pleasantly surprised 😄 `elm-pages` already supports YAML frontmatter. I just converts the frontmatter to JSON for the decoding in Elm, so you get the benefit of being able to write it in YAML if you prefer, but then use JSON decoders to parse it.

I just tend to use JSON for my examples because I've been bitten a few times by the implicit transformations that YAML does of your data in a few cases (like changing "yes" or "no" to boolean values, or automatically reformatting dates in surprising ways for example). But YAML is fully supported already for those who prefer it! 😄

**Comment by monacoremo** [comment]
Awesome, thanks! Need to try it out :-)

**Comment by Erudition** [comment]
Hi there! is this still the case?
