### ISSUE TITLE
Bug: links break when deploying to subdomains

### ISSUE THREAD

**Issue by cyberglot** [dillonkearns/elm-pages#69]
All links work fine if I deploy it to `example.com`, but they break if I deploy it to `example.com/blog`, e.g. a repository using github or gitlab pages.

**Comment by cyberglot** [comment]
I am happy to send a Pull Request fixing it.

**Comment by dillonkearns** [comment]
Hi @cyberglot! Thanks for reporting the issue! Ian also had a problem with that: https://github.com/dillonkearns/elm-pages/issues/15.

I would love to get this fixed, but I haven't thought deeply about what's going on and what the solution looks like. Do you have an idea what the fix would look like?

I would welcome a PR, or any insights you have on what's going on 😄

**Comment by cyberglot** [comment]
I believe the URL is being rewritten to point to the root domain. If you're ok witth it, I'd like to move all the URL manipulation to use [`elm/url`](https://package.elm-lang.org/packages/elm/url/latest/Url).

**Comment by dillonkearns** [comment]
Yeah, I'm definitely okay with using the `Url.Builder`. I think I tried using that at one point but for some reason went without it.

There are several cases in the code where it might be convenient to some custom helpers for joining together paths...

Something like

```elm
Path.join [ "/first/", "second", "/third" ] == "/first/second/third"
```

But that might be a separate issue. Just a little context in case you run into anything like that.

So at a high-level, what do you think the solution should be? It seems like the core problem is that `PagePath.toString` uses absolute URLs, right?

https://github.com/dillonkearns/elm-pages/blob/master/src/Pages/PagePath.elm#L113-L118

What would be best practice be? I can think of two approaches.

## 1) Explicit Cross-Origin URLs
Use full URLs, including the https://basesite.com, for all links, always explicitly using the full canonical URL as the base.

I wonder if there are any best practice reasons to avoid this? The `elm/url` package seems to try to encourage avoiding it by naming the function crossOrigin: https://package.elm-lang.org/packages/elm/url/latest/Url-Builder#crossOrigin. Are there other web best practice reasons against it?

There's one implementation detail to look out for here, which is that the link pre-fetching checks for absolute URLs. I guess it doesn't make a difference because it's already checking if the hosts match, so they should work whether they have the canonical site URL in the base or start with a `/`.

https://github.com/dillonkearns/elm-pages/blob/master/index.js#L141

## 2) Change `PagePath.toString` to take a base path
So for example if you're hosting your site at example.com/my-site, then you would call:

```elm
PagePath.toString [ "my-site" ] Pages.pages.blog.index
```

## 3) Pass in an base path with `Pages.Platform.application`
It could be passed in as part of a data structure that includes the `canonicalSiteUrl` as well.

Then it could be wired through from the `Pages.Platform.application`, and stored in the `Pages.pages` values so it could be used in the `PagePath.toString` function without explicitly wiring it in in the user code.


## Summary
I'm not sure if I'm totally off base here, those are just the first thoughts that come to mind. I'd be curious how other tools like Gatsby solve these problems. Any idea what the best practices are around this (i.e. what should we be doing at a high-level, should all links include the full base URL in them)?

**Comment by cyberglot** [comment]
I don't think we should go for the canonical URL, this will make local dev very painful -- unless you'd prefer to solve it differently for development and production. I have used nodejs a lot to generate static websites, so usually the best way is to use something that generates URLs consistently. It shouldn't be so hard given that we already have the generated `Pages.elm` to help with this.

**Comment by dillonkearns** [comment]
Yeah, avoiding the canonical URL at the base would be very nice, and you're right it would bring up cases like local development that would be a pain.

Here's the doc on what Gatsby does for this:

https://www.gatsbyjs.org/docs/path-prefix/

So sounds like it's just a matter of including that prefix in front of all URLs. So yeah, I guess something like option 3 would be the right approach.

**Comment by dillonkearns** [comment]
We'll probably need to set the `publicPath` in Webpack so it resolves the static files correctly as well. Fortunately, we can pass data through from the `Pages.Platform.application` config into webpack 👍

https://webpack.js.org/guides/public-path/

**Comment by cyberglot** [comment]
Alright, can I get into it or is it easier for you to do it?

**Comment by dillonkearns** [comment]
If you're up for giving it a shot, I'd love a PR on this!

Let me try to point you to a few places in the code to make it easier for you. And then feel free to ping me any time if you have questions.

**Comment by dillonkearns** [comment]
I think it would make sense to change the type here to be a record.

https://github.com/dillonkearns/elm-pages/blob/aef38a9a63f8382a849d3d74f807113b3f5055ea/src/Pages/Internal/Platform.elm#L720

So something like:

```
canonicalSiteUrl : {
    base : String
  , path : List String
}
```

Note that the type here is listed out explicitly instead of using a type alias. The reason it's duplicated a few different places is because Elm's error messages aren't very helpful when you use record type aliases.

**Comment by dillonkearns** [comment]
The `payload` value you get here is the value sent over from Elm:

https://github.com/dillonkearns/elm-pages/blob/5a1e06c729cbaaff443cb1a9c1da9cc6d7fc9d7d/generator/src/elm-pages.js#L88

The data comes from the CLI step here, so you could just change this type and wire through the appropriate data:

https://github.com/dillonkearns/elm-pages/blob/d22521a50dd24987eb9b86934bc1069b024e2d64/src/Pages/Internal/Platform/Cli.elm#L41

A little note about the architecture here. The app runs in two different states, a CLI phase, and a Browser phase. So we're actually running the app with the same config here, but as a CLI step. Pretty handy!

**Comment by dillonkearns** [comment]
You could then set the `publicPath` in Webpack based on the `Pages.Platform.application` options by taking the data from the `payload` and passing it in here:

https://github.com/dillonkearns/elm-pages/blob/e7dfab4cb22b8031322d38f5b5be4e9460ff9220/generator/src/develop.js#L35

**Comment by dillonkearns** [comment]
The first design that comes to mind for using the path prefix is to store it as part of the internals of the `PagePath.PagePath`:

https://github.com/dillonkearns/elm-pages/blob/313ae0e08c69ebcfb140b38370e4781f8d243c1e/src/Pages/PagePath.elm#L91

Then we'll have access to it when we call `PagePath.toString`.

Then we can just pass it in to this helper in the generated code:

https://github.com/dillonkearns/elm-pages/blob/dc29eb4ed6bec0f483f490729e36bc381f8aea3a/generator/src/elm-file-constants.js#L80

**Comment by dillonkearns** [comment]
We'll need to do something similar with `ImagePath`.

https://github.com/dillonkearns/elm-pages/blob/313ae0e08c69ebcfb140b38370e4781f8d243c1e/src/Pages/ImagePath.elm#L64

https://github.com/dillonkearns/elm-pages/blob/dc29eb4ed6bec0f483f490729e36bc381f8aea3a/generator/src/elm-file-constants.js#L74

**Comment by dillonkearns** [comment]
I think those are the key points.

I know there are a lot of moving parts to study to get up and running, so no pressure if you decide not to take it on right now, just let me know 😄

**Comment by cyberglot** [comment]
I am happy to do it asap because I'm deploying it to gitlab.

**Comment by icidasset** [comment]
Hey folks 👋 
I'd like to help with this as well.

I was thinking of passing this **"base path" as a flag**, mainly because we need the same static website to work on multiple domains and sub-directories. So **based on the url,** I'd check if I need to set a "base path" or not.

Does that make sense? Could do this in Elm as well, instead of a flag.

**Comment by cyberglot** [comment]
I have implemented it already 😄 I'm just struggling a little bit to test it locally since I'm not familiar on how to get a package to be included if it's not on elm-packages. Any tips?

My implementation basically goes like: you pass your whole URL according to elm/url up to paths. Then locally it uses relative links `blog/post/`, when it's built it becomes `protocol://yourdomain/basepath/blog/post/`. Let me knoe your thoughts.

**Comment by icidasset** [comment]
@cyberglot Not entirely sure on this, but I think that should work. What was the issue you had with that approach?

Regarding the implementation. So if I understand correctly, you're using the `canonicalSiteUrl` to build urls (eg. making them relative based on the canonical site url)? The issue I have with that, is that you have to know what the exact site url is going to be before hand. Right? I need to be able to deploy my site anywhere, and just have it work.

**Comment by dillonkearns** [comment]
@cyberglot thanks for working on this! I'm not sure I'm following what the API you're talking about would look like, could you share a small snippet?

What happened when you added `../elm-pages/src` to your source-directories? It seems like it should work, I use that same technique for the docs site. You can also use that docs site to iterate and experiment, that's what I do. It's all set up for local development to use the latest version of both the JS code and the Elm package code. You just `cd examples/docs && npm install && npm start`.

Here's the `elm.json` for the docs site:

https://github.com/dillonkearns/elm-pages/blob/master/examples/docs/elm.json#L3-L7

And here's how I have the docs site use the latest JS code:

https://github.com/dillonkearns/elm-pages/blob/master/examples/docs/package.json#L18

**Comment by cyberglot** [comment]
> Regarding the implementation. So if I understand correctly, you're using the `canonicalSiteUrl` to build urls (eg. making them relative based on the canonical site url)? The issue I have with that, is that you have to know what the exact site url is going to be before hand. Right? I need to be able to deploy my site anywhere, and just have it work.

@icidasset true, but all staticgens require a baseURL. we could potentially get the base URL when the webiste first loads `./index.html`, but I believe you can see that this is very fragile given that if someone accesses your website from an internal page, all your links are instantly broken. I believe github deals with that automatically by filling in the baseURL, but you won't have the same automatic treatment elsewhere -- I, for instance, am deploying to gitlab. 
My current work is [here](https://github.com/cyberglot/elm-pages/tree/new-urls). It still has a bug regarding replicating current path sometimes, but if you want to derive the base URL from the current knoweldge of pages and folders, please be my guest :)

**Comment by cyberglot** [comment]
@dillonkearns `main` function looks like this
```
Pages.Platform.application
        { init = \_ -> init
        , view = view
        , update = update
        , subscriptions = subscriptions
        , documents = [ markdownDocument ]
        , manifest = manifest
        , canonicalSiteUrl = CanonicalUrl "http" "cyberglot.gitlab.io" Nothing (Just "test")
        , onPageChange = \_ -> ()
        , generateFiles = generateFiles
        , internals = Pages.internals
        }
```
where `CanonicalUrl "http" "cyberglot.gitlab.io" Nothing (Just "test") = http://cyberglot.gitlab.io/test`. 

This way, the user can have a type safe canonical URL with ports and paths.
I could have made it a record, but I feel it's too much to type.
Or we could have an empty URL and have the user update the record, like this:
```
        , canonicalSiteUrl = { canonicalURL | protocol = "http"
                             , domain = "cyberglot.gitlab.io"
                             , path = "test"
                             }
```

**Comment by cyberglot** [comment]
@dillonkearns relating to testing, I have managed to have it working by adding all deps as direct deps, rather than indirect as it was.

**Comment by icidasset** [comment]
> but all staticgens require a baseURL

Most of the time it's **optional**, not required.

As it should be, because, for example, my company uses https://ipfs.io/
Which has a browser extension that caches your site offline and then the url changes.
```shell
https://example.com
# becomes
http://127.0.0.1:8080/ipns/example.com/
```

Basically the base path changes from `/` to `/ipns/example.com/`.
So we can't use a fixed base path.

> I believe you can see that this is very fragile given that if someone accesses your website from an internal page, all your links are instantly broken.

Hmm, not sure I understand. What do you mean exactly by `accesses your website from an internal page`? Can't injected javascript always override stuff in a way that it breaks something?

---

Also, I don't think we should use the "canonical site url" for this, since it's [designed for deduplicating content](https://en.wikipedia.org/wiki/Canonical_link_element).

**Comment by icidasset** [comment]
The simplest solution I can think of at the moment, is that we insert a `<base />` element on each page where the `href` attribute is a relative path to the root. So for example:
```shell
# Directory Structure
/index.js
/nested/index.html
/another/nested/index.html

# /nested/index.html
<base href="../" />
<a href="another/nested/index.html">Hello</a>
<script src="index.js" />

# will link correctly to the another/nested index html file
# and will load the index.js file on the root
```

This'll make `/nested/index.html` file believe it lives on the root (ie. `/index.html`).
So you can basically always use the entire path.

Thoughts?

**Comment by icidasset** [comment]
I started implementing that here: https://github.com/dillonkearns/elm-pages/compare/master...icidasset:base?expand=1

I seem to be having issues with `StaticHttp` requests, the `build` command gets stuck on 98%. Not sure if that's because of my new code here. When I remove the requests, it works fine.

Some notes:
- I probably missed some absolute urls
- I don't know where to change the `precache-manifest` url
- Node.js is so fragile 😤

**Comment by cyberglot** [comment]
@icidasset, your solution doesn't work for my problem. When I deploy to `example.com/test`, all links point to `example.com/somethingelse` and all assets point to `example.com`. And `<base />` is actually hard to deal, specially when we also want to support anchors.

**Comment by cyberglot** [comment]
I checked on gitlab and a `baseUrl` must be defined: [URLs and baseurls](https://docs.gitlab.com/ee/user/project/pages/getting_started_part_one.html#urls-and-baseurls). I don't know any other form to deal with subdirectories.

**Comment by icidasset** [comment]
@cyberglot My bad, I made a bunch of mistakes 🤦‍♂
Sorry about that. Can you please try again? 🙏 
https://github.com/dillonkearns/elm-pages/compare/master...icidasset:base?expand=1

---

> you’ll have to look for this configuration (base URL) on your SSG’s documentation and set it up to reflect this pattern

Reading that Gitlab documentation, it's a suggested configuration for several static-site generators. Not a requirement, right? The only thing that configuration does, is make absolute urls have a prefix (eg. "/gatsby/..." for https://pages.gitlab.io/gatsby/page-2/). I think we can do better than use absolute urls everywhere.

---

Also, sorry about the long discussion and everything.
I definitely want to find a solution that works great for everyone.

I've thought a bit more about this, and I think that:
- As I said before, using the canonical url for this is not a good idea. I don't think the web is supposed to work this way.
- I see two possible solutions: Either use `<base>` to make everything relative, or make elm-pages generate relative links (eg. the path itself is relative, `<a href="../page/link/" />`).
- There might be other solutions I haven't thought of. Please let me know if you have any ideas.

So far, the `<base>` solution I'm working on, seems the best, and easiest, overall. Every html document technically lives on the root, and works everywhere (if I don't mess it up that is).

I definitely agree regarding the anchors, that is a bit annoying. You'd have have to prefix those with the pathname as well, unfortunately. If we want to avoid this, we would opt for solution nr. 2 (every generated path is relative).

**Comment by cyberglot** [comment]
@icidasset I really want to find a way to make it better, I'm a fan of Protocol Labs'work and ipfs but I don't know how to solve it for static pages without an actual server engine :(

I don't think your solution with `<base/>` works for my problem? The root path isn't the root for my page, the subdirectory is.

**Comment by icidasset** [comment]
> I don't think your solution with <base/> works for my problem? The root path isn't the root for my page, the subdirectory is.

Oh, sorry for my poor choice of words! 😅 We're definitely solving the same issue here. I'm using a sub directory as the base as well.

How it works:
```shell
# Directory structure of static (elm) pages:
index.html                           # <base href="" />
nested/index.html                    # <base href="../" />
another/nested/index.html            # <base href="../../" />
```

This will work no matter where I put these files:
`http://localhost:3000/`, `https://example.io/sub-directory/` or `http://127.0.0.1:8080/ipns/example.io/`.

I'll continue my work on this asap and make a PR.

**Comment by cyberglot** [comment]
@icidasset so are you having a different `<base />` for each page? 🤔

**Comment by icidasset** [comment]
@cyberglot Yes exactly, automatically generated for you by elm-pages.

**Comment by dillonkearns** [comment]
[NPM package version](1.2.12](https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-NPM.md#1212---2020-03-28) and [Elm package version 4.0.1](https://github.com/dillonkearns/elm-pages/blob/master/CHANGELOG-ELM.md#401---2020-03-28) have been released with this fix! 🎉 

Thanks so much to both of you! 🙏
