### ISSUE TITLE
Self-host fonts with typefaces

### ISSUE THREAD

**Issue by kodeFant** [dillonkearns/elm-pages#94]
Hi!

In Gatsby projects i find it really easy to self host fonts with fonts from NPM packages.

```npm install typeface-roboto typeface-roboto-mono```

You could then for example remove the external google fonts export from the top of the `style.css` file in your docs example project.

Instead you could do these imports in the `index.js` file.

```javascript
import "typeface-roboto"
import "typeface-roboto-mono"
```

These fonts would then be self hosted and usable on the app just like that. This shaves off load time and greatly simplifies self hosting.

The Gatsy Creator has [written a about it here](https://github.com/KyleAMathews/typefaces)

All it seems to take is adding this line in the webpack config in develop.js:

```javascript
{
  test: /\.(woff|woff2|eot|ttf)$/,
  use: [
  { loader: 'file-loader' }
  ]
}
```

The fonts would then be built into the root of the build like this:
 
<img width="343" alt="Skjermbilde 2020-04-10 kl  11 26 55" src="https://user-images.githubusercontent.com/9317208/78980554-67dd1980-7b1e-11ea-83e7-3aedbb63656a.png">

The current page will only load the font files they require, so there will be no overfetching.

I see you already have a loader that takes in some fonts, but I didn't get it to work with typefaces by doing small modifications on it, so I figured I might as well just add that one.

Any thoughts on that feature? I have limited experience with webpack, but will gladly make a pull request if you wish!

**Comment by dillonkearns** [comment]
I think with the new beta build (which will be replacing the `elm-pages build` command in the near future), it makes sense to simply add a font asset to the `static/` folder, and then reference that from the entrypoint CSS file. The elm-pages beta build no longer uses webpack, and it's moved away from doing any sort of bunlding for the user, so there's no need for file loaders since it doesn't touch your CSS or JS entry points. I laid out my thinking about this in #148. I'd love to hear other thoughts if there's more to add on this topic, as this is still a developing idea.

Let's discuss further in #148 if there are more things to discuss. Thank you!

**Comment by kodeFant** [comment]
Going away from webpack sounds like an excellent choice! :+1:
